name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null

permissions:
  contents: read

jobs:
  playwright-test-shard:
    timeout-minutes: 60
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4, 5, 6, 7, 8, 9]
        shardTotal: [9]
    container:
      image: gwennlbh/playwright-bun:v1.58.2@sha256:4672fc0a5e52d6ec7f3c7047cd34a1e7ad701bd9408056befc4629a91bd01433
      options: --user 1001
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - name: Git Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup deno
        uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          deno-version-file: .dvmrc

      - name: Install dependencies
        run: deno install --frozen

      - name: Run Playwright tests
        run: deno task e2e --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}

      - name: Upload playwright report to GitHub Actions Artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: playwright-report-${{ matrix.shardIndex }}
          path: playwright-report/
          retention-days: 1

  playwright-tests:
    runs-on: ubuntu-24.04
    needs:
      - playwright-test-shard
    steps:
      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1
